### ISSUE TITLE
force close activity due couldn't find "libqdicteng.so"

### ISSUE THREAD

**Issue by shm-original** [namndev/QDict#6]
Hello and thanks for a nice dictionary app!
I try to build and run your application source code but when app runs it crash and force close by android OS , any idea how could i solve this problem?
I build and run your app in both android 6 and android 4.1.1 , in both version it crashed ,but when i install your app from google play store , it does not Seem to have any problem.

09-12 12:42:23.090 18090-18090/com.annie.dictionary E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.annie.dictionary, PID: 18090
                                                                      java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.annie.dictionary-1/base.apk"],nativeLibraryDirectories=[/data/app/com.annie.dictionary-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libqdicteng.so"
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                          at java.lang.System.loadLibrary(System.java:1076)
                                                                          at com.annie.dictionary.QDictEng.<clinit>(QDictEng.java:16)
                                                                          at com.annie.dictionary.QDictions.<init>(QDictions.java:35)
                                                                          at com.annie.dictionary.MainActivity.onRequestPermissionResult(MainActivity.java:282)
                                                                          at com.annie.dictionary.BaseActivity.checkPermission(BaseActivity.java:58)
                                                                          at com.annie.dictionary.MainActivity.onCreate(MainActivity.java:199)
                                                                          at android.app.Activity.performCreate(Activity.java:6251)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-12 12:42:23.094 886-27444/? W/ActivityManager:   Force finishing activity com.annie.dictionary/.MainActivity
09-12 12:42:23.115 886-27444/? W/ActivityManager:   Force finishing activity com.estrongs.android.pop/.app.InstallMonitorActivity
09-12 12:42:23.115 886-27444/? W/ActivityManager: Duplicate finish request for ActivityRecord{5e8645c u0 com.estrongs.android.pop/.app.InstallMonitorActivity t369 f}
09-12 12:42:23.140 18105-18105/? I/GAv4: Google Analytics 7.8.95 is starting up. To enable debug logging on a device run:
                                           adb shell setprop log.tag.GAv4 DEBUG

**Comment by shm-original** [comment]
i find the solution ,that was mentioned  [here](https://github.com/madmanteam/QDict/issues/1)

**Comment by marmistrz** [comment]
Confirming this,  QDict/qDict/src/main/java/com/annie/dictionary/QDictEng.java is trying to load library `qdicteng` which is no more.

**Comment by alexanderadam** [comment]
Hi @shm-origina,

would it be possible that you rename your fork containing the fix and put it on F-Droid so that [it can be used again](https://f-droid.org/wiki/page/com.annie.dictionary)?
